export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const CREATE_KATEGORI = "CREATE_KATEGORI";
export const GET_KATEGORI = "GET_KATEGORI";
export const GET_KATEGORI_ID = "GET_KATEGORI_ID";
export const UPDATE_KATEGORI = "UPDATE_KATEGORI";
export const DELETE_KATEGORI = "DELETE_KATEGORI";
export const OPEN_POPUP = "OPEN_POPUP";

export const CREATE_LOKASI = "CREATE_LOKASI";
export const GET_LOKASI = "GET_LOKASI";
export const GET_LOKASI_ID = "GET_LOKASI_ID";
export const UPDATE_LOKASI = "UPDATE_LOKASI";
export const DELETE_LOKASI = "DELETE_LOKASI";
export const OPEN_POPUP_LOKASI = "OPEN_POPUP_LOKASI";

export const CREATE_LABORATORIUM = "CREATE_LABORATORIUM";
export const GET_LABORATORIUM = "GET_LABORATORIUM";
export const GET_LAB = "GET_LAB";
export const GETLABALL = "GETLAB";
export const GET_LABORATORIUM_ID = "GET_LABORATORIUM_ID";
export const UPDATE_LABORATORIUM = "UPDATE_LABORATORIUM";
export const DELETE_LABORATORIUM = "DELETE_LABORATORIUM";

export const CREATE_ALAT = "CREATE_ALAT";
export const GET_ALAT = "GET_ALAT";
export const GET_ALAT_LAB = "GET_ALAT_LAB";
export const GET_ALAT_ID = "GET_ALAT_ID";
export const UPDATE_ALAT = "UPDATE_ALAT";
export const DELETE_ALAT = "DELETE_ALAT";

export const CREATE_PROFILE = "CREATE_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_ID = "GET_PROFILE_ID";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";

export const CREATE_PAGES = "CREATE_PAGES";
export const GET_PAGES = "GET_PAGES";
export const GET_PAGES_ID = "GET_PAGES_ID";
export const UPDATE_PAGES = "UPDATE_PAGES";
export const DELETE_PAGES = "DELETE_PAGES";

export const CREATE_USER = "CREATE_USER";
export const GET_USER = "GET_USER";
export const GET_USER_ID = "GET_USER_ID";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const CHECK_AUTH = "CHECK_AUTH";