export const GET_KATEGORI = "GET_KATEGORI";
export const GET_KATEGORI_ID = "GET_KATEGORI_ID";

export const GET_LOKASI_LIST = "GET_LOKASI_LIST";
export const GET_LAB_LIST = "GET_LAB_LIST";
export const GET_LABORATORIUM = "GET_LABORATORIUM";
export const GET_LABORATORIUM_ID = "GET_LABORATORIUM_ID";
export const GET_LABORATORIUM_CAT = "GET_LABORATORIUM_CAT";
export const GET_FILTER_LABORATORIUM = "GET_FILTER_LABORATORIUM";


export const GET_ALAT = "GET_ALAT";
export const GET_ALAT_ID = "GET_ALAT_ID";
export const GET_FILTER_ALAT = "GET_FILTER_ALAT";

export const GET_PAGE = "GET_PAGE";
export const GET_SLIDER = "GET_SLIDER";

